name: Run tests
on: push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   uses: lukka/get-cmake@latest

            -   name: Restore vcpkg
                uses: actions/cache@v4
                with:
                  path: |
                    ${{ env._VCPKG_ }}
                    !${{ env._VCPKG_ }}/buildtrees
                    !${{ env._VCPKG_ }}/packages
                    !${{ env._VCPKG_ }}/downloads
                    !${{ env._VCPKG_ }}/installed

                  key: |
                    ${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}

            -   name: Build
                run: cmake --build build

            -   name: Run tests
                run: ctest --test-dir build