name: Run tests
on: push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up vcpkg
                uses: lukka/setup-vcpkg@v1
                with:
                  vcpkgDirectory: '${{ runner.workspace }}/.vcpkg'
                  cleanAfterBuild: true

            -   name: Set up CMake
                uses: actions/setup-cmake@v3
                with:
                    cmake-version: '3.30'

            -   name: Install dependencies
                run: |
                    ./vcpkg/vcpkg install --feature-flags=manifests

            -   name: Configure cmake
                run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

            -   name: Build
                run: cmake --build build

            -   name: Run tests
                run: ctest --test-dir build